"""Tests for DAX measure data structures."""

from tqm.dax.measures import DAXMeasure, DAXMeasureSet


def test_measure_to_dax_block():
    m = DAXMeasure(
        name="Total Revenue",
        expression="SUMX(sales, sales[qty] * sales[unit_price])",
        table="sales",
        description="Kopējie ieņēmumi",
        format_string="#,##0.00 €",
        display_folder="Revenue",
    )
    block = m.to_dax_block()
    assert "Total Revenue" in block
    assert "SUMX" in block
    assert "Kopējie ieņēmumi" in block


def test_measure_to_tabular_editor_csharp():
    m = DAXMeasure(
        name="Total Revenue",
        expression="SUM(sales[amount])",
        table="sales",
        description="Test",
    )
    cs = m.to_tabular_editor_csharp()
    assert "AddMeasure" in cs
    assert "Total Revenue" in cs
    assert "sales" in cs


def test_measure_set_to_script():
    measures = [
        DAXMeasure("Revenue", "SUM(sales[amount])", "sales", display_folder="Revenue"),
        DAXMeasure("Cost", "SUM(sales[cost])", "sales", display_folder="Cost"),
    ]
    ms = DAXMeasureSet(fact_table="sales", measures=measures)
    script = ms.to_script()
    assert "Auto-generated by TQM" in script
    assert "Revenue" in script
    assert "Cost" in script


def test_measure_set_to_dax_file():
    measures = [
        DAXMeasure("Revenue", "SUM(sales[amount])", "sales"),
    ]
    ms = DAXMeasureSet(fact_table="sales", measures=measures)
    dax = ms.to_dax_file()
    assert "[Revenue]" in dax
    assert "SUM" in dax


def test_empty_measure_set():
    ms = DAXMeasureSet(fact_table="sales")
    assert ms.to_script() == "// Auto-generated by TQM — do not edit manually"
