"""DAX measure data types."""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class DAXMeasure:
    name: str
    expression: str
    table: str
    description: str = ""
    format_string: str = ""
    display_folder: str = ""

    def to_dax_block(self) -> str:
        """Return the full DAX measure definition block."""
        lines = [f"-- {self.description}" if self.description else ""]
        lines.append(f"[{self.name}] = {self.expression}")
        return "\n".join(l for l in lines if l)

    def to_tabular_editor_csharp(self) -> str:
        """Return C# snippet for Tabular Editor 2 scripting."""
        escaped = self.expression.replace('"', '\\"')
        desc = self.description.replace('"', '\\"')
        return (
            f'Model.Tables["{self.table}"].AddMeasure(\n'
            f'    "{self.name}",\n'
            f'    "{escaped}",\n'
            f'    "{self.display_folder}"\n'
            f').Description = "{desc}";\n'
        )


@dataclass
class DAXMeasureSet:
    fact_table: str
    measures: list[DAXMeasure] = field(default_factory=list)

    def to_script(self) -> str:
        """Full Tabular Editor C# script to create all measures."""
        lines = ["// Auto-generated by TQM — do not edit manually"]
        for m in self.measures:
            lines.append(m.to_tabular_editor_csharp())
        return "\n".join(lines)

    def to_dax_file(self) -> str:
        """Plain DAX measure file (usable in DAX Studio or PBIX)."""
        blocks = [m.to_dax_block() for m in self.measures]
        return "\n\n".join(blocks)
